### ISSUE TITLE
The type or namespace name 'Avaturn' does not exist in the namespace 'GLTFast'  

### ISSUE THREAD

**Issue by AaqibYounas** [avaturn/avaturn-unity-examples#1]
Unity Version : 2020.3.23f1
Platform : Android 

I encountered an issue after shifting my project from WebGL to Android. Initially, the project was working fine with the older versions of avaturnCore and avaturnInstaller. However, when I upgraded both avaturnCore and avaturnInstaller packages for Android, a new issue emerged.
that is  The type or namespace name 'Avaturn' does not exist in the namespace 'GLTFast'

**Comment by DmitryUlyanov** [comment]
@AaqibYounas fixed!
